---
tap_install:
  secrets:
    eso:
      vault:
        server: http://3.144.152.24:8200
        namespace: ""
        auth:
          kubernetes:
            mountPath: ipillai-run
            role: ipillai-run--tap-install-secrets
      remote_refs:
        tap_sensitive_values:
          sensitive_tap_values_yaml:
            key: secret/dev/ipillai-run/tap/sensitive-values.yaml
