
tap_install:
  values:
    shared:
      ingress_issuer: ""
      ingress_domain: tap.ipillaifull.tapscale.cloudfocused.in
    accelerator:
        server:
            service_type: ClusterIP
        ingress:
            include: true
    buildservice:
        kp_default_repository: tapscale.azurecr.io/ipillai/tkgi/buildservice
        kp_default_repository_secret:
            name: registry-credentials
            namespace: my-apps
    ceip_policy_disclosed: true
    contour:
        envoy:
            service:
                type: LoadBalancer
    grype:
        namespace: my-apps
        targetImagePullSecret: registry-credentials
    ootb_supply_chain_testing_scanning:
        gitops:
            ssh_secret: ""
        registry:
            repository: ipillai/tkgi/workload
            server: tapscale.azurecr.io
    profile: full
    supply_chain: testing_scanning
    metadata_store:
        ns_for_export_app_cert: "*"
        ingress_issuer: "tap-ingress-selfsigned"
    tap_telemetry:
        customer_entitlement_account_number: "123456789"
        installed_for_vmware_internal_use: "true"
        opt_out_of_telemetry: "false"
    namespace_provisioner:
      controller: true
      additional_sources:
      # Add templated Grype scan policy and java Tekton pipeline
      - git:
          ref: origin/main
          subPath: namespace-provisioner-gitops-examples/custom-resources/testing-scanning-supplychain
          url: https://github.com/dapdelivery/application-accelerator-samples.git
        path: _ytt_lib/testingscanning
      # Add templated snyk scan policy
      - git:
          ref: origin/main
          subPath: namespace-provisioner-gitops-examples/custom-resources/scanpolicies
          url: https://github.com/dapdelivery/application-accelerator-samples.git
        path: _ytt_lib/scanpolicies
    tap_gui:
      app_config:
        auth:
          allowGuestAccess: true
    crossplane:
      orphan_resources: false