---
secrets:
  eso:
    vault:
      server: http://3.144.152.24:8200
      namespace: ""
      auth:
        kubernetes:
          mountPath: ipillai-run
          role: ipillai-run--tanzu-sync-secrets
    remote_refs:
      sync_git:
        basic_auth:
          username:
            key: secret/dev/ipillai-run/tanzu-sync/sync-git/basic_auth
            property: username
          password:
            key: secret/dev/ipillai-run/tanzu-sync/sync-git/basic_auth
            property: password
      install_registry_dockerconfig:
        dockerconfigjson:
          key: secret/dev/ipillai-run/tanzu-sync/install-registry-dockerconfig
